characters = { list = ["abc", "xyz"], inverted = false }                    # a filter contains two attributes
copyrights = { list = ["arknights"], inverted = false }                     # list:     a list of strings where each element is a tag to be filtered
artists = { list = ["mourncolor", "elodias"], inverted = true }             # inverted: determins whether the values are filter out

# NOTE
# this filters spec only filters out folders from being created
# i.e. say you have 100 images, each image get sorted into 3 folders (for now)
#
# artists/<artistname>
# characters/<charactername>
# copyrights/<copyrights>
#
# with this set of filters, you can avoid the creation of <artist/character/copyright> folders.
# Cosider the below
# artists = { list = ["mourncolor", "elodias"], inverted = true }
# what this entails is that, for the artists folder,
# only mourncolor and elodias folders are created (note the inverted)
# if it wasn't inverted, then all artists folders except mounrcolor and elodias
# will be created
