# NOTE
# synonyms simply group several identical tags into a common tag
# for the purpose of unifying different conventions
# used across various booru providers

# use of synonyms help us defragment our file structure
# from running into issues like the following

# characters/
# |- kokomi/
# ||- XXX1.png
# ||- XXX2.png
# |- sangonomiya_kokomi/
# ||- YYY1.png
# ||- YYY2.png
# |- kokomi sangonomiya/
# ||- ZZZ1.png
# ||- ZZZ2.png

# clearly those are the same characters,
# but due the conventions used in their differing sources,
# they were separated into different folders.

# If we configured our synonyms to say
# kokomi = ["sangonomiya_kokomi" "kokomi sangonomiya"]
# we will then have a cleaner stucutre as follows

# characters/
# |- kokomi/
# ||- XXX1.png
# ||- XXX2.png
# ||- YYY1.png
# ||- YYY2.png
# ||- ZZZ1.png
# ||- ZZZ2.png

[synonyms.characters]
"sangonomiya_kokomi" = ["kokomi" "sangonomiya kokomi" "sangonomiya_kokomi_(genshin_impact)"]

[synonyms.tags]
"girl" = ["1girl" "female"]

[synonyms.copyrights]
"genshin_impact" = ["genshin impact", "yuanshen"]

[synonyms.artists]
"elodias" = ["little ello"]

[synonyms.ratings]
"e" = ["explicit", "n$fw"]
