# NOTE
# synonyms simply group several identical tags into a common tag
# for the purpose of unifying different conventions
# used across various booru providers

# use of synonyms help us defragment our file structure
# from running into issues like the following

# characters/
# |- kokomi/
# ||- XXX1.png
# ||- XXX2.png
# |- sangonomiya_kokomi/
# ||- YYY1.png
# ||- YYY2.png
# |- kokomi sangonomiya/
# ||- ZZZ1.png
# ||- ZZZ2.png

# clearly those are the same characters,
# but due the conventions used in their differing sources,
# they were separated into different folders.

# If we configured our synonyms to say
# character [{main = "kokomi", synonyms = ["sangonomiya_kokomi", "kokomi sangonomiya"]]
# we will then have a cleaner stucutre as follows

# characters/
# |- kokomi/
# ||- XXX1.png
# ||- XXX2.png
# ||- YYY1.png
# ||- YYY2.png
# ||- ZZZ1.png
# ||- ZZZ2.png

[synonyms]
characters = [
  {main = "sangonomiya_kokomi", synonyms = ["kokomi", "sangonomiya kokomi", "sangonomiya_kokomi_(genshin_impact)"]},
  {main = "yoimiya", synonyms = ["yoi", "fireworks_girl"]}
]
tags = [ {main = "girl", synonyms = ["1girl", "female"]} ]
copyrights = [{main = "genshin_impact", synonyms = ["genshin impact", "yuanshen"]}]
artists = [{main = "elodias", synonyms = ["little ello"]}]
ratings = [{main = "e", synonyms = ["explicit", "n$fw"]}]
