name: "Haskell Tests"
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '**.hs'
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix develop --command cabal test --test-show-details=direct
